source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘better' do
    pod 'Alamofire', '~> 4.0'
    pod 'Kingfisher', '~> 3.0'
    pod 'AlamofireObjectMapper', '~> 4.0'
end

